version: "2"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./config:/etc/nginx/conf.d/
      - /var/run/docker.sock:/tmp/docker.sock:ro      
      - ./vhosts.d:/etc/nginx/vhost.d/
      - /usr/share/nginx/html
    restart: always
  le:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx__le
    volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./certs:/etc/nginx/certs:rw
    volumes_from:
      - nginx-proxy
    restart: always
networks:
  default:
    external:
      name: nginx-proxy
